#!/bin/bash
echo "Phase 2: Updating all import statements..."

set -e

echo "Updating imports for App.tsx -> App.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*App.tsx'|from 'frontend/admin/src/App.tsx'|g"
echo "Updating imports for main.tsx -> main.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*frontend/legacy-root-src/main.tsx'|from 'frontend/admin/src/main.tsx'|g"
echo "Updating imports for main.tsx -> main.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*main.tsx'|from 'frontend/admin/src/main.tsx'|g"
echo "Updating imports for AnalyticsTab.tsx -> AnalyticsTab.jsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*frontend/legacy-root-src/AnalyticsTab.tsx'|from 'components/AnalyticsTab.jsx'|g"
echo "Updating imports for index.tsx -> index.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/elite/index.tsx'|from 'components/index.tsx'|g"
echo "Updating imports for index.tsx -> index.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/lazy/index.tsx'|from 'components/index.tsx'|g"
echo "Updating imports for index.tsx -> index.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/MoneyMaker/index.tsx'|from 'components/index.tsx'|g"
echo "Updating imports for index.tsx -> index.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/index.tsx'|from 'components/index.tsx'|g"
echo "Updating imports for index.tsx -> index.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/user-friendly/index.tsx'|from 'components/index.tsx'|g"
echo "Updating imports for index.tsx -> index.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*index.tsx'|from 'components/index.tsx'|g"
echo "Updating imports for index.tsx -> index.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*interfaces/index.tsx'|from 'components/index.tsx'|g"
echo "Updating imports for index.tsx -> index.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*pages/index.tsx'|from 'components/index.tsx'|g"
echo "Updating imports for index.tsx -> index.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/index.tsx'|from 'components/index.tsx'|g"
echo "Updating imports for ConcurrentFeaturesProvider.tsx -> ConcurrentFeaturesProvider.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*app/ConcurrentFeaturesProvider.tsx'|from 'app/ConcurrentFeaturesProvider.tsx'|g"
echo "Updating imports for ModernStateProvider.tsx -> ModernStateProvider.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*app/ModernStateProvider.tsx'|from 'app/ModernStateProvider.tsx'|g"
echo "Updating imports for AuthContext.tsx -> AuthContext.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*contexts/AuthContext.tsx'|from 'auth/AuthContext.tsx'|g"
echo "Updating imports for AuthContext.tsx -> AuthContext.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*contexts/__mocks__/AuthContext.tsx'|from 'auth/AuthContext.tsx'|g"
echo "Updating imports for AuthContext.tsx -> AuthContext.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*AuthContext.tsx'|from 'auth/AuthContext.tsx'|g"
echo "Updating imports for AllFeatures.test.tsx -> AllFeatures.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/AllFeatures.test.tsx'|from 'components/base/AllFeatures.test.tsx'|g"
echo "Updating imports for AllFeatures.test.tsx -> AllFeatures.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*test/integration/AllFeatures.test.tsx'|from 'components/base/AllFeatures.test.tsx'|g"
echo "Updating imports for ApiDebug.tsx -> ApiDebug.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ApiDebug.tsx'|from 'components/ApiDebug.tsx'|g"
echo "Updating imports for ApiErrorBoundary.tsx -> ApiErrorBoundary.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ApiErrorBoundary.tsx'|from 'components/ApiErrorBoundary.tsx'|g"
echo "Updating imports for AppInitializer.tsx -> AppInitializer.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/core/AppInitializer.tsx'|from 'components/AppInitializer.tsx'|g"
echo "Updating imports for AppInitializer.tsx -> AppInitializer.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/AppInitializer.tsx'|from 'components/AppInitializer.tsx'|g"
echo "Updating imports for ArbitragePage.test.tsx -> ArbitragePage.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ArbitragePage.test.tsx'|from 'components/ArbitragePage.test.tsx'|g"
echo "Updating imports for ArbitragePage.tsx -> ArbitragePage.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ArbitragePage.tsx'|from 'components/ArbitragePage.tsx'|g"
echo "Updating imports for AuthLayout.tsx -> AuthLayout.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*layouts/AuthLayout.tsx'|from 'components/AuthLayout.tsx'|g"
echo "Updating imports for AuthLayout.tsx -> AuthLayout.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/AuthLayout.tsx'|from 'components/AuthLayout.tsx'|g"
echo "Updating imports for AuthProvider.tsx -> AuthProvider.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*providers/AuthProvider.tsx'|from 'components/AuthProvider.tsx'|g"
echo "Updating imports for AuthProvider.tsx -> AuthProvider.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/AuthProvider.tsx'|from 'components/AuthProvider.tsx'|g"
echo "Updating imports for AuthProvider.tsx -> AuthProvider.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*AuthProvider.tsx'|from 'components/AuthProvider.tsx'|g"
echo "Updating imports for BackendConnectionTest.tsx -> BackendConnectionTest.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/debug/BackendConnectionTest.tsx'|from 'components/BackendConnectionTest.tsx'|g"
echo "Updating imports for BackendConnectionTest.tsx -> BackendConnectionTest.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BackendConnectionTest.tsx'|from 'components/BackendConnectionTest.tsx'|g"
echo "Updating imports for BankrollManager.tsx -> BankrollManager.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/features/user/BankrollManager.tsx'|from 'components/features/bankroll/BankrollManager.tsx'|g"
echo "Updating imports for BankrollManager.tsx -> BankrollManager.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/BankrollManager.tsx'|from 'components/features/bankroll/BankrollManager.tsx'|g"
echo "Updating imports for BankrollManager.tsx -> BankrollManager.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BankrollManager.tsx'|from 'components/features/bankroll/BankrollManager.tsx'|g"
echo "Updating imports for BankrollPage.test.tsx -> BankrollPage.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BankrollPage.test.tsx'|from 'components/BankrollPage.test.tsx'|g"
echo "Updating imports for BetSlip.tsx -> BetSlip.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/betting/BetSlip.tsx'|from 'components/BetSlip.tsx'|g"
echo "Updating imports for BettingOpportunities.tsx -> BettingOpportunities.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/BettingOpportunities.tsx'|from 'components/features/betting/BettingOpportunities.tsx'|g"
echo "Updating imports for BettingOpportunities.tsx -> BettingOpportunities.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/betting/BettingOpportunities.tsx'|from 'components/features/betting/BettingOpportunities.tsx'|g"
echo "Updating imports for BettingOpportunities.tsx -> BettingOpportunities.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/predictions/BettingOpportunities.tsx'|from 'components/features/betting/BettingOpportunities.tsx'|g"
echo "Updating imports for BettingOpportunities.tsx -> BettingOpportunities.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingOpportunities.tsx'|from 'components/features/betting/BettingOpportunities.tsx'|g"
echo "Updating imports for BettingStats.tsx -> BettingStats.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/BettingStats.tsx'|from 'components/features/betting/BettingStats.tsx'|g"
echo "Updating imports for BettingStats.tsx -> BettingStats.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/betting/BettingStats.tsx'|from 'components/features/betting/BettingStats.tsx'|g"
echo "Updating imports for BettingStats.tsx -> BettingStats.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingStats.tsx'|from 'components/features/betting/BettingStats.tsx'|g"
echo "Updating imports for BookmakerAnalysis.tsx -> BookmakerAnalysis.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BookmakerAnalysis.tsx'|from 'components/BookmakerAnalysis.tsx'|g"
echo "Updating imports for ConfidenceIndicator.jsx -> ConfidenceIndicator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/ConfidenceIndicator.jsx'|from 'components/features/predictions/ConfidenceIndicator.tsx'|g"
echo "Updating imports for ConfidenceIndicator.tsx -> ConfidenceIndicator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/ConfidenceIndicator.tsx'|from 'components/features/predictions/ConfidenceIndicator.tsx'|g"
echo "Updating imports for ConfidenceIndicator.tsx -> ConfidenceIndicator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/predictions/ConfidenceIndicator.tsx'|from 'components/features/predictions/ConfidenceIndicator.tsx'|g"
echo "Updating imports for ConfidenceIndicator.tsx -> ConfidenceIndicator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/common/ConfidenceIndicator.tsx'|from 'components/features/predictions/ConfidenceIndicator.tsx'|g"
echo "Updating imports for ConfidenceIndicator.tsx -> ConfidenceIndicator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ConfidenceIndicator.tsx'|from 'components/features/predictions/ConfidenceIndicator.tsx'|g"
echo "Updating imports for ConnectionStatus.tsx -> ConnectionStatus.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ConnectionStatus.tsx'|from 'components/ConnectionStatus.tsx'|g"
echo "Updating imports for ConnectionTest.tsx -> ConnectionTest.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ConnectionTest.tsx'|from 'components/ConnectionTest.tsx'|g"
echo "Updating imports for DebugApiStatus.tsx -> DebugApiStatus.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/DebugApiStatus.tsx'|from 'components/DebugApiStatus.tsx'|g"
echo "Updating imports for DebugPanel.tsx -> DebugPanel.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/DebugPanel.tsx'|from 'components/DebugPanel.tsx'|g"
echo "Updating imports for DevelopmentGuide.tsx -> DevelopmentGuide.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/DevelopmentGuide.tsx'|from 'components/DevelopmentGuide.tsx'|g"
echo "Updating imports for EnhancedDashboard.tsx -> EnhancedDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/EnhancedDashboard.tsx'|from 'components/features/dashboard/EnhancedDashboard.tsx'|g"
echo "Updating imports for EnhancedErrorBoundary.tsx -> EnhancedErrorBoundary.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/EnhancedErrorBoundary.tsx'|from 'components/EnhancedErrorBoundary.tsx'|g"
echo "Updating imports for EnhancedPropCard.tsx -> EnhancedPropCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/EnhancedPropCard.tsx'|from 'components/EnhancedPropCard.tsx'|g"
echo "Updating imports for EntryCard.tsx -> EntryCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EntryCard.tsx'|from 'components/EntryCard.tsx'|g"
echo "Updating imports for ErrorFallback.tsx -> ErrorFallback.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/feedback/ErrorFallback.tsx'|from 'components/ErrorFallback.tsx'|g"
echo "Updating imports for ErrorFallback.tsx -> ErrorFallback.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ErrorFallback.tsx'|from 'components/ErrorFallback.tsx'|g"
echo "Updating imports for ESPNHeadlinesTicker.tsx -> ESPNHeadlinesTicker.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/features/news/ESPNHeadlinesTicker.tsx'|from 'components/features/modern/ESPNHeadlinesTicker.tsx'|g"
echo "Updating imports for ESPNHeadlinesTicker.tsx -> ESPNHeadlinesTicker.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/ESPNHeadlinesTicker.tsx'|from 'components/features/modern/ESPNHeadlinesTicker.tsx'|g"
echo "Updating imports for ESPNHeadlinesTicker.tsx -> ESPNHeadlinesTicker.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ESPNHeadlinesTicker.tsx'|from 'components/features/modern/ESPNHeadlinesTicker.tsx'|g"
echo "Updating imports for featureCoverage.test.tsx -> featureCoverage.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/featureCoverage.test.tsx'|from 'components/featureCoverage.test.tsx'|g"
echo "Updating imports for featureCoverage.test.tsx -> featureCoverage.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*test/featureCoverage.test.tsx'|from 'components/featureCoverage.test.tsx'|g"
echo "Updating imports for FeatureStatusPanel.tsx -> FeatureStatusPanel.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/FeatureStatusPanel.tsx'|from 'components/FeatureStatusPanel.tsx'|g"
echo "Updating imports for FilterBar.tsx -> FilterBar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/common/FilterBar.tsx'|from 'components/FilterBar.tsx'|g"
echo "Updating imports for FilterBar.tsx -> FilterBar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/FilterBar.tsx'|from 'components/FilterBar.tsx'|g"
echo "Updating imports for Header.tsx -> Header.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Header.tsx'|from 'components/features/modern/Header.tsx'|g"
echo "Updating imports for Header.tsx -> Header.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/Header.tsx'|from 'components/features/modern/Header.tsx'|g"
echo "Updating imports for InjuryTracker.tsx -> InjuryTracker.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/InjuryTracker.tsx'|from 'components/features/injuries/InjuryTracker.tsx'|g"
echo "Updating imports for IntegrationStatus.tsx -> IntegrationStatus.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/IntegrationStatus.tsx'|from 'components/IntegrationStatus.tsx'|g"
echo "Updating imports for LineupBuilder.tsx -> LineupBuilder.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/LineupBuilder.tsx'|from 'components/features/lineup/LineupBuilder.tsx'|g"
echo "Updating imports for LineupComparisonTable.tsx -> LineupComparisonTable.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/LineupComparisonTable.tsx'|from 'components/LineupComparisonTable.tsx'|g"
echo "Updating imports for LiveOddsTicker.tsx -> LiveOddsTicker.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/betting/LiveOddsTicker.tsx'|from 'components/LiveOddsTicker.tsx'|g"
echo "Updating imports for LiveOddsTicker.tsx -> LiveOddsTicker.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/LiveOddsTicker.tsx'|from 'components/LiveOddsTicker.tsx'|g"
echo "Updating imports for LoadingOverlay.tsx -> LoadingOverlay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/LoadingOverlay.tsx'|from 'components/LoadingOverlay.tsx'|g"
echo "Updating imports for LoadingScreen.tsx -> LoadingScreen.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/core/LoadingScreen.tsx'|from 'components/LoadingScreen.tsx'|g"
echo "Updating imports for LoadingScreen.tsx -> LoadingScreen.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/LoadingScreen.tsx'|from 'components/LoadingScreen.tsx'|g"
echo "Updating imports for LoginForm.tsx -> LoginForm.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/auth/LoginForm.tsx'|from 'components/LoginForm.tsx'|g"
echo "Updating imports for LoginForm.tsx -> LoginForm.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/LoginForm.tsx'|from 'components/LoginForm.tsx'|g"
echo "Updating imports for MarketAnalysisDashboard.tsx -> MarketAnalysisDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MarketAnalysisDashboard.tsx'|from 'components/MarketAnalysisDashboard.tsx'|g"
echo "Updating imports for MLFactorViz.tsx -> MLFactorViz.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/MLFactorViz.tsx'|from 'components/features/analytics/MLFactorViz.tsx'|g"
echo "Updating imports for MLFactorViz.tsx -> MLFactorViz.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MLFactorViz.tsx'|from 'components/features/analytics/MLFactorViz.tsx'|g"
echo "Updating imports for MLPredictions.tsx -> MLPredictions.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MLPredictions.tsx'|from 'components/MLPredictions.tsx'|g"
echo "Updating imports for ModelPerformance.tsx -> ModelPerformance.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/ModelPerformance.tsx'|from 'components/features/analytics/ModelPerformance.tsx'|g"
echo "Updating imports for ModelPerformance.tsx -> ModelPerformance.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/predictions/ModelPerformance.tsx'|from 'components/features/analytics/ModelPerformance.tsx'|g"
echo "Updating imports for ModelPerformance.tsx -> ModelPerformance.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ModelPerformance.tsx'|from 'components/features/analytics/ModelPerformance.tsx'|g"
echo "Updating imports for NewsHub.tsx -> NewsHub.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/NewsHub.tsx'|from 'components/features/news/NewsHub.tsx'|g"
echo "Updating imports for NoResultsFallback.tsx -> NoResultsFallback.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/NoResultsFallback.tsx'|from 'components/NoResultsFallback.tsx'|g"
echo "Updating imports for OllamaStatus.tsx -> OllamaStatus.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/OllamaStatus.tsx'|from 'components/OllamaStatus.tsx'|g"
echo "Updating imports for PatternRecognition.tsx -> PatternRecognition.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/PatternRecognition.tsx'|from 'components/features/predictions/PatternRecognition.tsx'|g"
echo "Updating imports for PatternRecognition.tsx -> PatternRecognition.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PatternRecognition.tsx'|from 'components/features/predictions/PatternRecognition.tsx'|g"
echo "Updating imports for PayoutPreview.test.tsx -> PayoutPreview.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PayoutPreview.test.tsx'|from 'components/PayoutPreview.test.tsx'|g"
echo "Updating imports for PayoutPreview.tsx -> PayoutPreview.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/betting/PayoutPreview.tsx'|from 'components/PayoutPreview.tsx'|g"
echo "Updating imports for PayoutPreview.tsx -> PayoutPreview.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/lineup/PayoutPreview.tsx'|from 'components/PayoutPreview.tsx'|g"
echo "Updating imports for PayoutPreview.tsx -> PayoutPreview.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/prediction/PayoutPreview.tsx'|from 'components/PayoutPreview.tsx'|g"
echo "Updating imports for PayoutPreview.tsx -> PayoutPreview.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PayoutPreview.tsx'|from 'components/PayoutPreview.tsx'|g"
echo "Updating imports for PerformanceAnalytics.tsx -> PerformanceAnalytics.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/PerformanceAnalytics.tsx'|from 'components/features/analytics/PerformanceAnalytics.tsx'|g"
echo "Updating imports for PerformanceAnalytics.tsx -> PerformanceAnalytics.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PerformanceAnalytics.tsx'|from 'components/features/analytics/PerformanceAnalytics.tsx'|g"
echo "Updating imports for PerformanceMetrics.tsx -> PerformanceMetrics.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/PerformanceMetrics.tsx'|from 'components/features/analytics/PerformanceMetrics.tsx'|g"
echo "Updating imports for PerformanceMetrics.tsx -> PerformanceMetrics.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/betting/PerformanceMetrics.tsx'|from 'components/features/analytics/PerformanceMetrics.tsx'|g"
echo "Updating imports for PerformanceMetrics.tsx -> PerformanceMetrics.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/observability/PerformanceMetrics.tsx'|from 'components/features/analytics/PerformanceMetrics.tsx'|g"
echo "Updating imports for PerformanceMetrics.tsx -> PerformanceMetrics.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PerformanceMetrics.tsx'|from 'components/features/analytics/PerformanceMetrics.tsx'|g"
echo "Updating imports for PerformanceMonitor.tsx -> PerformanceMonitor.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/PerformanceMonitor.tsx'|from 'components/features/analytics/PerformanceMonitor.tsx'|g"
echo "Updating imports for PerformanceMonitor.tsx -> PerformanceMonitor.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PerformanceMonitor.tsx'|from 'components/features/analytics/PerformanceMonitor.tsx'|g"
echo "Updating imports for PerformanceMonitoringDashboard.tsx -> PerformanceMonitoringDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/phase4/PerformanceMonitoringDashboard.tsx'|from 'components/PerformanceMonitoringDashboard.tsx'|g"
echo "Updating imports for PlayerDashboard.tsx -> PlayerDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/player/PlayerDashboard.tsx'|from 'components/PlayerDashboard.tsx'|g"
echo "Updating imports for PredictionDisplay.tsx -> PredictionDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/PredictionDisplay.tsx'|from 'components/features/predictions/PredictionDisplay.tsx'|g"
echo "Updating imports for PredictionDisplay.tsx -> PredictionDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/prediction/PredictionDisplay.tsx'|from 'components/features/predictions/PredictionDisplay.tsx'|g"
echo "Updating imports for PredictionDisplay.tsx -> PredictionDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PredictionDisplay.tsx'|from 'components/features/predictions/PredictionDisplay.tsx'|g"
echo "Updating imports for PredictionEnhancement.tsx -> PredictionEnhancement.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/PredictionEnhancement.tsx'|from 'components/features/predictions/PredictionEnhancement.tsx'|g"
echo "Updating imports for PredictionEnhancement.tsx -> PredictionEnhancement.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PredictionEnhancement.tsx'|from 'components/features/predictions/PredictionEnhancement.tsx'|g"
echo "Updating imports for PropAnalysis.tsx -> PropAnalysis.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PropAnalysis.tsx'|from 'components/PropAnalysis.tsx'|g"
echo "Updating imports for PropCard.tsx -> PropCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/features/betting/PropCard.tsx'|from 'components/features/modern/PropCard.tsx'|g"
echo "Updating imports for PropCard.tsx -> PropCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/PropCard.tsx'|from 'components/features/modern/PropCard.tsx'|g"
echo "Updating imports for PropCard.tsx -> PropCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/PropCard.tsx'|from 'components/features/modern/PropCard.tsx'|g"
echo "Updating imports for PropCard.tsx -> PropCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PropCard.tsx'|from 'components/features/modern/PropCard.tsx'|g"
echo "Updating imports for PropCards.tsx -> PropCards.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/features/betting/PropCards.tsx'|from 'components/features/modern/PropCards.tsx'|g"
echo "Updating imports for PropCards.tsx -> PropCards.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/PropCards.tsx'|from 'components/features/modern/PropCards.tsx'|g"
echo "Updating imports for PropCards.tsx -> PropCards.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PropCards.tsx'|from 'components/features/modern/PropCards.tsx'|g"
echo "Updating imports for PropGPT.tsx -> PropGPT.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PropGPT.tsx'|from 'components/PropGPT.tsx'|g"
echo "Updating imports for PropList.tsx -> PropList.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/lists/PropList.tsx'|from 'components/PropList.tsx'|g"
echo "Updating imports for PropList.tsx -> PropList.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PropList.tsx'|from 'components/PropList.tsx'|g"
echo "Updating imports for QuantumAI.tsx -> QuantumAI.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/QuantumAI.tsx'|from 'components/features/quantum/QuantumAI.tsx'|g"
echo "Updating imports for RealtimePredictionDisplay.tsx -> RealtimePredictionDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/RealtimePredictionDisplay.tsx'|from 'components/features/predictions/RealtimePredictionDisplay.tsx'|g"
echo "Updating imports for RealtimePredictionDisplay.tsx -> RealtimePredictionDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/predictions/RealtimePredictionDisplay.tsx'|from 'components/features/predictions/RealtimePredictionDisplay.tsx'|g"
echo "Updating imports for RealtimePredictionDisplay.tsx -> RealtimePredictionDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RealtimePredictionDisplay.tsx'|from 'components/features/predictions/RealtimePredictionDisplay.tsx'|g"
echo "Updating imports for RealTimeUpdates.tsx -> RealTimeUpdates.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RealTimeUpdates.tsx'|from 'components/RealTimeUpdates.tsx'|g"
echo "Updating imports for RegisterForm.tsx -> RegisterForm.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/auth/RegisterForm.tsx'|from 'components/RegisterForm.tsx'|g"
echo "Updating imports for RegisterForm.tsx -> RegisterForm.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RegisterForm.tsx'|from 'components/RegisterForm.tsx'|g"
echo "Updating imports for RiskManagerPage.test.tsx -> RiskManagerPage.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RiskManagerPage.test.tsx'|from 'components/RiskManagerPage.test.tsx'|g"
echo "Updating imports for RiskManagerPage.tsx -> RiskManagerPage.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*pages/RiskManagerPage.tsx'|from 'components/RiskManagerPage.tsx'|g"
echo "Updating imports for RiskManagerPage.tsx -> RiskManagerPage.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RiskManagerPage.tsx'|from 'components/RiskManagerPage.tsx'|g"
echo "Updating imports for RiskProfileManager.tsx -> RiskProfileManager.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/RiskProfileManager.tsx'|from 'components/features/user/RiskProfileManager.tsx'|g"
echo "Updating imports for RiskProfileManager.tsx -> RiskProfileManager.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/risk/RiskProfileManager.tsx'|from 'components/features/user/RiskProfileManager.tsx'|g"
echo "Updating imports for RiskProfileManager.tsx -> RiskProfileManager.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RiskProfileManager.tsx'|from 'components/features/user/RiskProfileManager.tsx'|g"
echo "Updating imports for RiskProfileSelector.tsx -> RiskProfileSelector.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/RiskProfileSelector.tsx'|from 'components/features/user/RiskProfileSelector.tsx'|g"
echo "Updating imports for RiskProfileSelector.tsx -> RiskProfileSelector.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/betting/RiskProfileSelector.tsx'|from 'components/features/user/RiskProfileSelector.tsx'|g"
echo "Updating imports for RiskProfileSelector.tsx -> RiskProfileSelector.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RiskProfileSelector.tsx'|from 'components/features/user/RiskProfileSelector.tsx'|g"
echo "Updating imports for SHAPAnalysis.tsx -> SHAPAnalysis.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/SHAPAnalysis.tsx'|from 'components/features/shap/SHAPAnalysis.tsx'|g"
echo "Updating imports for ShapBreakdownModal.tsx -> ShapBreakdownModal.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/ShapBreakdownModal.tsx'|from 'components/features/analytics/ShapBreakdownModal.tsx'|g"
echo "Updating imports for ShapBreakdownModal.tsx -> ShapBreakdownModal.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ShapBreakdownModal.tsx'|from 'components/features/analytics/ShapBreakdownModal.tsx'|g"
echo "Updating imports for ShapValueDisplay.tsx -> ShapValueDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/ShapValueDisplay.tsx'|from 'components/features/analytics/ShapValueDisplay.tsx'|g"
echo "Updating imports for ShapValueDisplay.tsx -> ShapValueDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/predictions/ShapValueDisplay.tsx'|from 'components/features/analytics/ShapValueDisplay.tsx'|g"
echo "Updating imports for ShapValueDisplay.tsx -> ShapValueDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ShapValueDisplay.tsx'|from 'components/features/analytics/ShapValueDisplay.tsx'|g"
echo "Updating imports for ShapVisualization.tsx -> ShapVisualization.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/ShapVisualization.tsx'|from 'components/features/analytics/ShapVisualization.tsx'|g"
echo "Updating imports for SimpleToaster.tsx -> SimpleToaster.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SimpleToaster.tsx'|from 'components/SimpleToaster.tsx'|g"
echo "Updating imports for SmartControlsBar.tsx -> SmartControlsBar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/controls/SmartControlsBar.tsx'|from 'components/SmartControlsBar.tsx'|g"
echo "Updating imports for SmartControlsBar.tsx -> SmartControlsBar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/SmartControlsBar.tsx'|from 'components/SmartControlsBar.tsx'|g"
echo "Updating imports for SocialIntelligence.tsx -> SocialIntelligence.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/SocialIntelligence.tsx'|from 'components/features/social/SocialIntelligence.tsx'|g"
echo "Updating imports for StrategyAutomationToggle.tsx -> StrategyAutomationToggle.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/StrategyAutomationToggle.tsx'|from 'components/StrategyAutomationToggle.tsx'|g"
echo "Updating imports for ThemeDemo.tsx -> ThemeDemo.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ThemeDemo.tsx'|from 'components/ThemeDemo.tsx'|g"
echo "Updating imports for ThemeToggle.tsx -> ThemeToggle.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/navigation/ThemeToggle.tsx'|from 'components/ThemeToggle.tsx'|g"
echo "Updating imports for ThemeToggle.tsx -> ThemeToggle.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/common/ThemeToggle.tsx'|from 'components/ThemeToggle.tsx'|g"
echo "Updating imports for ThemeToggle.tsx -> ThemeToggle.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/ThemeToggle/ThemeToggle.tsx'|from 'components/ThemeToggle.tsx'|g"
echo "Updating imports for ThemeToggle.tsx -> ThemeToggle.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ThemeToggle.tsx'|from 'components/ThemeToggle.tsx'|g"
echo "Updating imports for ToastContext.tsx -> ToastContext.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/feedback/ToastContext.tsx'|from 'components/ToastContext.tsx'|g"
echo "Updating imports for ToastContext.tsx -> ToastContext.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ToastContext.tsx'|from 'components/ToastContext.tsx'|g"
echo "Updating imports for ToggleSidebar.tsx -> ToggleSidebar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ToggleSidebar.tsx'|from 'components/ToggleSidebar.tsx'|g"
echo "Updating imports for TrendingProps.tsx -> TrendingProps.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/TrendingProps.tsx'|from 'components/TrendingProps.tsx'|g"
echo "Updating imports for UserConstraintsForm.tsx -> UserConstraintsForm.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/UserConstraintsForm.tsx'|from 'components/features/user/UserConstraintsForm.tsx'|g"
echo "Updating imports for UserConstraintsForm.tsx -> UserConstraintsForm.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UserConstraintsForm.tsx'|from 'components/features/user/UserConstraintsForm.tsx'|g"
echo "Updating imports for UserProfile.tsx -> UserProfile.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/user-friendly/UserProfile.tsx'|from 'components/UserProfile.tsx'|g"
echo "Updating imports for WeatherStation.tsx -> WeatherStation.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/WeatherStation.tsx'|from 'components/features/WeatherStation.tsx'|g"
echo "Updating imports for WebSocketBatchingAnalytics.tsx -> WebSocketBatchingAnalytics.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/WebSocketBatchingAnalytics.tsx'|from 'components/WebSocketBatchingAnalytics.tsx'|g"
echo "Updating imports for WebSocketLoadBalancerAnalytics.tsx -> WebSocketLoadBalancerAnalytics.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/WebSocketLoadBalancerAnalytics.tsx'|from 'components/WebSocketLoadBalancerAnalytics.tsx'|g"
echo "Updating imports for WebSocketSecurityDashboard.tsx -> WebSocketSecurityDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/WebSocketSecurityDashboard.tsx'|from 'components/WebSocketSecurityDashboard.tsx'|g"
echo "Updating imports for withErrorBoundary.tsx -> withErrorBoundary.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/common/ErrorBoundary/withErrorBoundary.tsx'|from 'components/withErrorBoundary.tsx'|g"
echo "Updating imports for withErrorBoundary.tsx -> withErrorBoundary.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/withErrorBoundary.tsx'|from 'components/withErrorBoundary.tsx'|g"
echo "Updating imports for AdminSettings.tsx -> AdminSettings.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/AdminSettings.tsx'|from 'components/admin/AdminSettings.tsx'|g"
echo "Updating imports for ErrorLogs.tsx -> ErrorLogs.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ErrorLogs.tsx'|from 'components/admin/ErrorLogs.tsx'|g"
echo "Updating imports for ModelSettings.tsx -> ModelSettings.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ModelSettings.tsx'|from 'components/admin/ModelSettings.tsx'|g"
echo "Updating imports for WhatIfSimulator.tsx -> WhatIfSimulator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/WhatIfSimulator.tsx'|from 'components/advanced/WhatIfSimulator.tsx'|g"
echo "Updating imports for AnalyticsDashboard.test.tsx -> AnalyticsDashboard.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/AnalyticsDashboard.test.tsx'|from 'components/analytics/AnalyticsDashboard.test.tsx'|g"
echo "Updating imports for ClusteringInsights.tsx -> ClusteringInsights.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ClusteringInsights.tsx'|from 'components/analytics/ClusteringInsights.tsx'|g"
echo "Updating imports for EnsembleInsights.tsx -> EnsembleInsights.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EnsembleInsights.tsx'|from 'components/analytics/EnsembleInsights.tsx'|g"
echo "Updating imports for HyperMLInsights.tsx -> HyperMLInsights.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/HyperMLInsights.tsx'|from 'components/analytics/HyperMLInsights.tsx'|g"
echo "Updating imports for MLInsights.tsx -> MLInsights.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/analytics/MLInsights.tsx'|from 'components/features/analytics/MLInsights.tsx'|g"
echo "Updating imports for MLInsights.tsx -> MLInsights.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/insights/MLInsights.tsx'|from 'components/features/analytics/MLInsights.tsx'|g"
echo "Updating imports for MLInsights.tsx -> MLInsights.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MLInsights.tsx'|from 'components/features/analytics/MLInsights.tsx'|g"
echo "Updating imports for ModelComparison.tsx -> ModelComparison.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ModelComparison.tsx'|from 'components/analytics/ModelComparison.tsx'|g"
echo "Updating imports for ModelComparisonChart.tsx -> ModelComparisonChart.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ModelComparisonChart.tsx'|from 'components/analytics/ModelComparisonChart.tsx'|g"
echo "Updating imports for ModelPerformanceDashboard.tsx -> ModelPerformanceDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ModelPerformanceDashboard.tsx'|from 'components/analytics/ModelPerformanceDashboard.tsx'|g"
echo "Updating imports for PerformanceAlerts.tsx -> PerformanceAlerts.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PerformanceAlerts.tsx'|from 'components/analytics/PerformanceAlerts.tsx'|g"
echo "Updating imports for PerformanceExport.tsx -> PerformanceExport.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PerformanceExport.tsx'|from 'components/analytics/PerformanceExport.tsx'|g"
echo "Updating imports for PredictionConfidenceGraph.tsx -> PredictionConfidenceGraph.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PredictionConfidenceGraph.tsx'|from 'components/analytics/PredictionConfidenceGraph.tsx'|g"
echo "Updating imports for RealTimeAccuracyDashboard.tsx -> RealTimeAccuracyDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RealTimeAccuracyDashboard.tsx'|from 'components/analytics/RealTimeAccuracyDashboard.tsx'|g"
echo "Updating imports for RealTimeMetrics.tsx -> RealTimeMetrics.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RealTimeMetrics.tsx'|from 'components/analytics/RealTimeMetrics.tsx'|g"
echo "Updating imports for RiskAssessmentMatrix.tsx -> RiskAssessmentMatrix.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RiskAssessmentMatrix.tsx'|from 'components/analytics/RiskAssessmentMatrix.tsx'|g"
echo "Updating imports for RiskInsights.tsx -> RiskInsights.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RiskInsights.tsx'|from 'components/analytics/RiskInsights.tsx'|g"
echo "Updating imports for ShapExplanation.tsx -> ShapExplanation.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/prediction/ShapExplanation.tsx'|from 'components/analytics/ShapExplanation.tsx'|g"
echo "Updating imports for ShapExplanation.tsx -> ShapExplanation.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ShapExplanation.tsx'|from 'components/analytics/ShapExplanation.tsx'|g"
echo "Updating imports for SHAPInsight.tsx -> SHAPInsight.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SHAPInsight.tsx'|from 'components/analytics/SHAPInsight.tsx'|g"
echo "Updating imports for TimeSeriesInsights.tsx -> TimeSeriesInsights.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/TimeSeriesInsights.tsx'|from 'components/analytics/TimeSeriesInsights.tsx'|g"
echo "Updating imports for UltraMLInsights.tsx -> UltraMLInsights.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UltraMLInsights.tsx'|from 'components/analytics/UltraMLInsights.tsx'|g"
echo "Updating imports for UserStats.tsx -> UserStats.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/analytics/UserStats.tsx'|from 'components/features/user/UserStats.tsx'|g"
echo "Updating imports for UserStats.tsx -> UserStats.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UserStats.tsx'|from 'components/features/user/UserStats.tsx'|g"
echo "Updating imports for UserStatsSafe.tsx -> UserStatsSafe.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UserStatsSafe.tsx'|from 'components/analytics/UserStatsSafe.tsx'|g"
echo "Updating imports for ShapExplanation.test.tsx -> ShapExplanation.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/prediction/ShapExplanation.test.tsx'|from 'components/analytics/ShapExplanation.test.tsx'|g"
echo "Updating imports for RealTimeAPIIntegrationDashboard.tsx -> RealTimeAPIIntegrationDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RealTimeAPIIntegrationDashboard.tsx'|from 'components/api/RealTimeAPIIntegrationDashboard.tsx'|g"
echo "Updating imports for AuthPage.tsx -> AuthPage.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*pages/AuthPage.tsx'|from 'components/auth/AuthPage.tsx'|g"
echo "Updating imports for AuthPage.tsx -> AuthPage.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*AuthPage.tsx'|from 'components/auth/AuthPage.tsx'|g"
echo "Updating imports for PasswordChangeForm.tsx -> PasswordChangeForm.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*PasswordChangeForm.tsx'|from 'components/auth/PasswordChangeForm.tsx'|g"
echo "Updating imports for ProtectedRoute.tsx -> ProtectedRoute.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/layout/ProtectedRoute.tsx'|from 'components/auth/ProtectedRoute.tsx'|g"
echo "Updating imports for ProtectedRoute.tsx -> ProtectedRoute.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ProtectedRoute.tsx'|from 'components/auth/ProtectedRoute.tsx'|g"
echo "Updating imports for UnifiedAuth.tsx -> UnifiedAuth.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UnifiedAuth.tsx'|from 'components/auth/UnifiedAuth.tsx'|g"
echo "Updating imports for Alert.tsx -> Alert.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Alert.tsx'|from 'components/base/Alert.tsx'|g"
echo "Updating imports for Alert.tsx -> Alert.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Alert.tsx'|from 'components/base/Alert.tsx'|g"
echo "Updating imports for Badge.tsx -> Badge.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Badge.tsx'|from 'components/base/Badge.tsx'|g"
echo "Updating imports for Badge.tsx -> Badge.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Badge.tsx'|from 'components/base/Badge.tsx'|g"
echo "Updating imports for BetRecommendationCard.test.tsx -> BetRecommendationCard.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/prediction/BetRecommendationCard.test.tsx'|from 'components/base/BetRecommendationCard.test.tsx'|g"
echo "Updating imports for Button.tsx -> Button.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Button.tsx'|from 'components/base/Button.tsx'|g"
echo "Updating imports for Button.tsx -> Button.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Button.tsx'|from 'components/base/Button.tsx'|g"
echo "Updating imports for Card.tsx -> Card.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Card.tsx'|from 'components/base/Card.tsx'|g"
echo "Updating imports for Card.tsx -> Card.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Card.tsx'|from 'components/base/Card.tsx'|g"
echo "Updating imports for EnhancedPropCard.test.tsx -> EnhancedPropCard.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/EnhancedPropCard.test.tsx'|from 'components/base/EnhancedPropCard.test.tsx'|g"
echo "Updating imports for Input.tsx -> Input.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Input.tsx'|from 'components/base/Input.tsx'|g"
echo "Updating imports for Input.tsx -> Input.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Input.tsx'|from 'components/base/Input.tsx'|g"
echo "Updating imports for Label.tsx -> Label.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/Label.tsx'|from 'components/base/Label.tsx'|g"
echo "Updating imports for Layout.tsx -> Layout.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/core/Layout.tsx'|from 'components/base/Layout.tsx'|g"
echo "Updating imports for Layout.tsx -> Layout.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/core/Layout/Layout.tsx'|from 'components/base/Layout.tsx'|g"
echo "Updating imports for Layout.tsx -> Layout.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/layout/Layout.tsx'|from 'components/base/Layout.tsx'|g"
echo "Updating imports for Layout.tsx -> Layout.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/common/layout/Layout.tsx'|from 'components/base/Layout.tsx'|g"
echo "Updating imports for OptimizedPropList.fixed.tsx -> OptimizedPropList.fixed.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/optimized/OptimizedPropList.fixed.tsx'|from 'components/base/OptimizedPropList.fixed.tsx'|g"
echo "Updating imports for Progress.tsx -> Progress.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Progress.tsx'|from 'components/base/Progress.tsx'|g"
echo "Updating imports for Select.tsx -> Select.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Select.tsx'|from 'components/base/Select.tsx'|g"
echo "Updating imports for Skeleton.tsx -> Skeleton.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Skeleton.tsx'|from 'components/base/Skeleton.tsx'|g"
echo "Updating imports for SkeletonLoader.tsx -> SkeletonLoader.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SkeletonLoader.tsx'|from 'components/base/SkeletonLoader.tsx'|g"
echo "Updating imports for Switch.tsx -> Switch.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Switch.tsx'|from 'components/base/Switch.tsx'|g"
echo "Updating imports for Tabs.tsx -> Tabs.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Tabs.tsx'|from 'components/base/Tabs.tsx'|g"
echo "Updating imports for Toast.tsx -> Toast.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Toast.tsx'|from 'components/base/Toast.tsx'|g"
echo "Updating imports for Toast.tsx -> Toast.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*Toast.tsx'|from 'components/base/Toast.tsx'|g"
echo "Updating imports for Toaster.tsx -> Toaster.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/Toaster.tsx'|from 'components/base/Toaster.tsx'|g"
echo "Updating imports for Toaster.tsx -> Toaster.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Toaster.tsx'|from 'components/base/Toaster.tsx'|g"
echo "Updating imports for Toaster.tsx -> Toaster.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*Toaster.tsx'|from 'components/base/Toaster.tsx'|g"
echo "Updating imports for Tooltip.tsx -> Tooltip.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Tooltip.tsx'|from 'components/base/Tooltip.tsx'|g"
echo "Updating imports for BestBetSelector.tsx -> BestBetSelector.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BestBetSelector.tsx'|from 'components/betting/BestBetSelector.tsx'|g"
echo "Updating imports for BetForm.tsx -> BetForm.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BetForm.tsx'|from 'components/betting/BetForm.tsx'|g"
echo "Updating imports for BetHistory.tsx -> BetHistory.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BetHistory.tsx'|from 'components/betting/BetHistory.tsx'|g"
echo "Updating imports for BettingAnalytics.tsx -> BettingAnalytics.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingAnalytics.tsx'|from 'components/betting/BettingAnalytics.tsx'|g"
echo "Updating imports for BettingDataSource.tsx -> BettingDataSource.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingDataSource.tsx'|from 'components/betting/BettingDataSource.tsx'|g"
echo "Updating imports for BettingInterface.tsx -> BettingInterface.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingInterface.tsx'|from 'components/betting/BettingInterface.tsx'|g"
echo "Updating imports for BettingModal.tsx -> BettingModal.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingModal.tsx'|from 'components/betting/BettingModal.tsx'|g"
echo "Updating imports for BettingSettingsContainer.tsx -> BettingSettingsContainer.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingSettingsContainer.tsx'|from 'components/betting/BettingSettingsContainer.tsx'|g"
echo "Updating imports for BettingSettingsPanel.tsx -> BettingSettingsPanel.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingSettingsPanel.tsx'|from 'components/betting/BettingSettingsPanel.tsx'|g"
echo "Updating imports for BettingSettingsSummary.tsx -> BettingSettingsSummary.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingSettingsSummary.tsx'|from 'components/betting/BettingSettingsSummary.tsx'|g"
echo "Updating imports for EventList.tsx -> EventList.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EventList.tsx'|from 'components/betting/EventList.tsx'|g"
echo "Updating imports for KellyCalculator.tsx -> KellyCalculator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/betting/KellyCalculator.tsx'|from 'components/features/risk/KellyCalculator.tsx'|g"
echo "Updating imports for KellyCalculator.tsx -> KellyCalculator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/KellyCalculator.tsx'|from 'components/features/risk/KellyCalculator.tsx'|g"
echo "Updating imports for ModelSelector.tsx -> ModelSelector.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ModelSelector.tsx'|from 'components/betting/ModelSelector.tsx'|g"
echo "Updating imports for OddsDisplay.tsx -> OddsDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/OddsDisplay.tsx'|from 'components/betting/OddsDisplay.tsx'|g"
echo "Updating imports for PrizePicksEdgeDisplay.tsx -> PrizePicksEdgeDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PrizePicksEdgeDisplay.tsx'|from 'components/betting/PrizePicksEdgeDisplay.tsx'|g"
echo "Updating imports for PrizePicksInterface.tsx -> PrizePicksInterface.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PrizePicksInterface.tsx'|from 'components/betting/PrizePicksInterface.tsx'|g"
echo "Updating imports for SHAPVisualization.tsx -> SHAPVisualization.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/SHAPVisualization.tsx'|from 'components/betting/SHAPVisualization.tsx'|g"
echo "Updating imports for SHAPVisualization.tsx -> SHAPVisualization.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SHAPVisualization.tsx'|from 'components/betting/SHAPVisualization.tsx'|g"
echo "Updating imports for SportSelector.tsx -> SportSelector.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/common/SportSelector.tsx'|from 'components/betting/SportSelector.tsx'|g"
echo "Updating imports for SportSelector.tsx -> SportSelector.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SportSelector.tsx'|from 'components/betting/SportSelector.tsx'|g"
echo "Updating imports for StakeSizingControl.tsx -> StakeSizingControl.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/StakeSizingControl.tsx'|from 'components/betting/StakeSizingControl.tsx'|g"
echo "Updating imports for UnifiedBettingHistory.tsx -> UnifiedBettingHistory.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UnifiedBettingHistory.tsx'|from 'components/betting/UnifiedBettingHistory.tsx'|g"
echo "Updating imports for BettingOpportunityCard.tsx -> BettingOpportunityCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/betting/BettingOpportunityCard.tsx'|from 'components/betting/BettingOpportunityCard.tsx'|g"
echo "Updating imports for BettingCard.tsx -> BettingCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingCard.tsx'|from 'components/builder/BettingCard.tsx'|g"
echo "Updating imports for BuilderIntegrationTest.tsx -> BuilderIntegrationTest.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BuilderIntegrationTest.tsx'|from 'components/builder/BuilderIntegrationTest.tsx'|g"
echo "Updating imports for BuilderPage.tsx -> BuilderPage.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BuilderPage.tsx'|from 'components/builder/BuilderPage.tsx'|g"
echo "Updating imports for PerformanceChart.tsx -> PerformanceChart.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/charts/PerformanceChart.tsx'|from 'components/features/analytics/PerformanceChart.tsx'|g"
echo "Updating imports for PerformanceChart.tsx -> PerformanceChart.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/monitoring/PerformanceChart.tsx'|from 'components/features/analytics/PerformanceChart.tsx'|g"
echo "Updating imports for PerformanceChart.tsx -> PerformanceChart.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PerformanceChart.tsx'|from 'components/features/analytics/PerformanceChart.tsx'|g"
echo "Updating imports for SmartControlsBar.test.tsx -> SmartControlsBar.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SmartControlsBar.test.tsx'|from 'components/controls/SmartControlsBar.test.tsx'|g"
echo "Updating imports for AppShell.tsx -> AppShell.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/core/AppShell.tsx'|from 'components/features/modern/AppShell.tsx'|g"
echo "Updating imports for AppShell.tsx -> AppShell.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/layout/AppShell.tsx'|from 'components/features/modern/AppShell.tsx'|g"
echo "Updating imports for AppShell.tsx -> AppShell.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/AppShell.tsx'|from 'components/features/modern/AppShell.tsx'|g"
echo "Updating imports for ErrorBoundary.tsx -> ErrorBoundary.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/ErrorBoundary.tsx'|from 'components/core/ErrorBoundary.tsx'|g"
echo "Updating imports for ErrorBoundary.tsx -> ErrorBoundary.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/common/ErrorBoundary.tsx'|from 'components/core/ErrorBoundary.tsx'|g"
echo "Updating imports for ErrorState.tsx -> ErrorState.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ErrorState.tsx'|from 'components/core/ErrorState.tsx'|g"
echo "Updating imports for LoadingState.tsx -> LoadingState.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/LoadingState.tsx'|from 'components/core/LoadingState.tsx'|g"
echo "Updating imports for Navbar.tsx -> Navbar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/core/Navbar/Navbar.tsx'|from 'components/core/Navbar.tsx'|g"
echo "Updating imports for Navbar.tsx -> Navbar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Navbar/Navbar.tsx'|from 'components/core/Navbar.tsx'|g"
echo "Updating imports for Navbar.tsx -> Navbar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/navigation/Navbar.tsx'|from 'components/core/Navbar.tsx'|g"
echo "Updating imports for Navbar.tsx -> Navbar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/common/layout/Navbar.tsx'|from 'components/core/Navbar.tsx'|g"
echo "Updating imports for Navbar.tsx -> Navbar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/Navbar.tsx'|from 'components/core/Navbar.tsx'|g"
echo "Updating imports for Navigation.tsx -> Navigation.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/layout/Navigation.tsx'|from 'components/core/Navigation.tsx'|g"
echo "Updating imports for Navigation.tsx -> Navigation.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/layout/Navigation.tsx'|from 'components/core/Navigation.tsx'|g"
echo "Updating imports for Navigation.tsx -> Navigation.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/Navigation.tsx'|from 'components/core/Navigation.tsx'|g"
echo "Updating imports for Sidebar.tsx -> Sidebar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/core/Sidebar.tsx'|from 'components/core/Sidebar.tsx'|g"
echo "Updating imports for Sidebar.tsx -> Sidebar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/navigation/Sidebar.tsx'|from 'components/core/Sidebar.tsx'|g"
echo "Updating imports for Sidebar.tsx -> Sidebar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/common/layout/Sidebar.tsx'|from 'components/core/Sidebar.tsx'|g"
echo "Updating imports for Sidebar.tsx -> Sidebar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/Sidebar/Sidebar.tsx'|from 'components/core/Sidebar.tsx'|g"
echo "Updating imports for Sidebar.tsx -> Sidebar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/Sidebar.tsx'|from 'components/core/Sidebar.tsx'|g"
echo "Updating imports for CyberAnalyticsHub.tsx -> CyberAnalyticsHub.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/CyberAnalyticsHub.tsx'|from 'components/cyber/CyberAnalyticsHub.tsx'|g"
echo "Updating imports for CyberMLDashboard.tsx -> CyberMLDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/CyberMLDashboard.tsx'|from 'components/cyber/CyberMLDashboard.tsx'|g"
echo "Updating imports for AIEdgeML.tsx -> AIEdgeML.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/AIEdgeML.tsx'|from 'components/elite/AIEdgeML.tsx'|g"
echo "Updating imports for BusinessAnalysis.tsx -> BusinessAnalysis.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BusinessAnalysis.tsx'|from 'components/elite/BusinessAnalysis.tsx'|g"
echo "Updating imports for EnhancedAPITestDashboard.tsx -> EnhancedAPITestDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EnhancedAPITestDashboard.tsx'|from 'components/enhanced/EnhancedAPITestDashboard.tsx'|g"
echo "Updating imports for EnhancedPrizePicks.tsx -> EnhancedPrizePicks.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EnhancedPrizePicks.tsx'|from 'components/enhanced/EnhancedPrizePicks.tsx'|g"
echo "Updating imports for UnifiedEventDetails.tsx -> UnifiedEventDetails.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UnifiedEventDetails.tsx'|from 'components/events/UnifiedEventDetails.tsx'|g"
echo "Updating imports for Arbitrage.tsx -> Arbitrage.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/Arbitrage.tsx'|from 'components/features/betting/Arbitrage.tsx'|g"
echo "Updating imports for ArbitrageDetector.tsx -> ArbitrageDetector.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ArbitrageDetector.tsx'|from 'components/features/betting/ArbitrageDetector.tsx'|g"
echo "Updating imports for BetBuilder.test.tsx -> BetBuilder.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BetBuilder.test.tsx'|from 'components/features/betting/BetBuilder.test.tsx'|g"
echo "Updating imports for BetBuilder.tsx -> BetBuilder.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BetBuilder.tsx'|from 'components/features/betting/BetBuilder.tsx'|g"
echo "Updating imports for BetSlipSidebar.tsx -> BetSlipSidebar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BetSlipSidebar.tsx'|from 'components/features/betting/BetSlipSidebar.tsx'|g"
echo "Updating imports for BettingOpportunity.tsx -> BettingOpportunity.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingOpportunity.tsx'|from 'components/features/betting/BettingOpportunity.tsx'|g"
echo "Updating imports for BettingRecommendations.tsx -> BettingRecommendations.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingRecommendations.tsx'|from 'components/features/betting/BettingRecommendations.tsx'|g"
echo "Updating imports for EntryTracking.tsx -> EntryTracking.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/features/tracking/EntryTracking.tsx'|from 'components/features/modern/EntryTracking.tsx'|g"
echo "Updating imports for EntryTracking.tsx -> EntryTracking.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EntryTracking.tsx'|from 'components/features/modern/EntryTracking.tsx'|g"
echo "Updating imports for Modals.tsx -> Modals.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/common/modals/Modals.tsx'|from 'components/features/modern/Modals.tsx'|g"
echo "Updating imports for Modals.tsx -> Modals.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/Modals.tsx'|from 'components/features/modern/Modals.tsx'|g"
echo "Updating imports for BankrollMetrics.tsx -> BankrollMetrics.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BankrollMetrics.tsx'|from 'components/features/user/BankrollMetrics.tsx'|g"
echo "Updating imports for BankrollStats.tsx -> BankrollStats.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BankrollStats.tsx'|from 'components/features/user/BankrollStats.tsx'|g"
echo "Updating imports for FeedbackWidget.tsx -> FeedbackWidget.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/feedback/FeedbackWidget.tsx'|from 'components/feedback/FeedbackWidget.tsx'|g"
echo "Updating imports for FeedbackWidget.tsx -> FeedbackWidget.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/FeedbackWidget.tsx'|from 'components/feedback/FeedbackWidget.tsx'|g"
echo "Updating imports for BettingFilters.tsx -> BettingFilters.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/betting/BettingFilters.tsx'|from 'components/filters/BettingFilters.tsx'|g"
echo "Updating imports for CompactFilterBar.tsx -> CompactFilterBar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/CompactFilterBar.tsx'|from 'components/filters/CompactFilterBar.tsx'|g"
echo "Updating imports for FluentLiveFilters.tsx -> FluentLiveFilters.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/FluentLiveFilters.tsx'|from 'components/filters/FluentLiveFilters.tsx'|g"
echo "Updating imports for InGameTimeFilter.tsx -> InGameTimeFilter.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/InGameTimeFilter.tsx'|from 'components/filters/InGameTimeFilter.tsx'|g"
echo "Updating imports for QuantumFilters.tsx -> QuantumFilters.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/QuantumFilters.tsx'|from 'components/filters/QuantumFilters.tsx'|g"
echo "Updating imports for EnhancedIntelligenceViews.tsx -> EnhancedIntelligenceViews.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EnhancedIntelligenceViews.tsx'|from 'components/intelligence/EnhancedIntelligenceViews.tsx'|g"
echo "Updating imports for EnhancedModuleManagement.tsx -> EnhancedModuleManagement.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EnhancedModuleManagement.tsx'|from 'components/intelligence/EnhancedModuleManagement.tsx'|g"
echo "Updating imports for EnhancedModuleSection.tsx -> EnhancedModuleSection.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EnhancedModuleSection.tsx'|from 'components/intelligence/EnhancedModuleSection.tsx'|g"
echo "Updating imports for ModuleEnhancement.tsx -> ModuleEnhancement.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ModuleEnhancement.tsx'|from 'components/intelligence/ModuleEnhancement.tsx'|g"
echo "Updating imports for ModuleEnhancements.tsx -> ModuleEnhancements.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ModuleEnhancements.tsx'|from 'components/intelligence/ModuleEnhancements.tsx'|g"
echo "Updating imports for AdvancedSidebar.tsx -> AdvancedSidebar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/AdvancedSidebar.tsx'|from 'components/layout/AdvancedSidebar.tsx'|g"
echo "Updating imports for CyberHeader.tsx -> CyberHeader.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/CyberHeader.tsx'|from 'components/layout/CyberHeader.tsx'|g"
echo "Updating imports for CyberLayout.tsx -> CyberLayout.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/CyberLayout.tsx'|from 'components/layout/CyberLayout.tsx'|g"
echo "Updating imports for CyberSidebar.tsx -> CyberSidebar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/CyberSidebar.tsx'|from 'components/layout/CyberSidebar.tsx'|g"
echo "Updating imports for EliteSportsHeader.tsx -> EliteSportsHeader.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EliteSportsHeader.tsx'|from 'components/layout/EliteSportsHeader.tsx'|g"
echo "Updating imports for EnhancedModernLayout.tsx -> EnhancedModernLayout.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EnhancedModernLayout.tsx'|from 'components/layout/EnhancedModernLayout.tsx'|g"
echo "Updating imports for SmartLineupBuilder.tsx -> SmartLineupBuilder.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SmartLineupBuilder.tsx'|from 'components/lineup/SmartLineupBuilder.tsx'|g"
echo "Updating imports for SavedLineups.tsx -> SavedLineups.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SavedLineups.tsx'|from 'components/lineups/SavedLineups.tsx'|g"
echo "Updating imports for MarketIntelligence.tsx -> MarketIntelligence.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MarketIntelligence.tsx'|from 'components/market/MarketIntelligence.tsx'|g"
echo "Updating imports for CyberTheme.tsx -> CyberTheme.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/CyberTheme.tsx'|from 'components/mega/CyberTheme.tsx'|g"
echo "Updating imports for MegaAdminPanel.tsx -> MegaAdminPanel.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MegaAdminPanel.tsx'|from 'components/mega/MegaAdminPanel.tsx'|g"
echo "Updating imports for MegaLayout.tsx -> MegaLayout.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MegaLayout.tsx'|from 'components/mega/MegaLayout.tsx'|g"
echo "Updating imports for MegaPrizePicks.tsx -> MegaPrizePicks.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MegaPrizePicks.tsx'|from 'components/mega/MegaPrizePicks.tsx'|g"
echo "Updating imports for MegaUI.tsx -> MegaUI.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MegaUI.tsx'|from 'components/mega/MegaUI.tsx'|g"
echo "Updating imports for MobileOptimizedInterface.tsx -> MobileOptimizedInterface.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MobileOptimizedInterface.tsx'|from 'components/mobile/MobileOptimizedInterface.tsx'|g"
echo "Updating imports for MonitoringDashboard.tsx -> MonitoringDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MonitoringDashboard.tsx'|from 'components/monitoring/MonitoringDashboard.tsx'|g"
echo "Updating imports for PerformanceAlert.tsx -> PerformanceAlert.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PerformanceAlert.tsx'|from 'components/monitoring/PerformanceAlert.tsx'|g"
echo "Updating imports for PerformanceAlertContainer.tsx -> PerformanceAlertContainer.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PerformanceAlertContainer.tsx'|from 'components/monitoring/PerformanceAlertContainer.tsx'|g"
echo "Updating imports for UnifiedNavigation.tsx -> UnifiedNavigation.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UnifiedNavigation.tsx'|from 'components/navigation/UnifiedNavigation.tsx'|g"
echo "Updating imports for UltraAccuracyOverview.tsx -> UltraAccuracyOverview.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UltraAccuracyOverview.tsx'|from 'components/overview/UltraAccuracyOverview.tsx'|g"
echo "Updating imports for OnboardingFlow.tsx -> OnboardingFlow.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*onboarding/OnboardingFlow.tsx'|from 'components/phase4/OnboardingFlow.tsx'|g"
echo "Updating imports for StatusIndicator.tsx -> StatusIndicator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/StatusIndicator.tsx'|from 'components/phase4/StatusIndicator.tsx'|g"
echo "Updating imports for AdvancedConfidenceVisualizer.tsx -> AdvancedConfidenceVisualizer.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/AdvancedConfidenceVisualizer.tsx'|from 'components/prediction/AdvancedConfidenceVisualizer.tsx'|g"
echo "Updating imports for BetRecommendationCard.tsx -> BetRecommendationCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BetRecommendationCard.tsx'|from 'components/prediction/BetRecommendationCard.tsx'|g"
echo "Updating imports for BetRecommendationList.tsx -> BetRecommendationList.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BetRecommendationList.tsx'|from 'components/prediction/BetRecommendationList.tsx'|g"
echo "Updating imports for MoneyMakerResults.tsx -> MoneyMakerResults.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MoneyMakerResults.tsx'|from 'components/prediction/MoneyMakerResults.tsx'|g"
echo "Updating imports for PredictionExplanationModal.tsx -> PredictionExplanationModal.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PredictionExplanationModal.tsx'|from 'components/prediction/PredictionExplanationModal.tsx'|g"
echo "Updating imports for PredictionForm.tsx -> PredictionForm.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PredictionForm.tsx'|from 'components/prediction/PredictionForm.tsx'|g"
echo "Updating imports for QuantumPredictionsInterface.tsx -> QuantumPredictionsInterface.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/QuantumPredictionsInterface.tsx'|from 'components/prediction/QuantumPredictionsInterface.tsx'|g"
echo "Updating imports for ShapValueBar.tsx -> ShapValueBar.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ShapValueBar.tsx'|from 'components/prediction/ShapValueBar.tsx'|g"
echo "Updating imports for UltraAccuracyDashboard.tsx -> UltraAccuracyDashboard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UltraAccuracyDashboard.tsx'|from 'components/prediction/UltraAccuracyDashboard.tsx'|g"
echo "Updating imports for UncertaintyIndicator.tsx -> UncertaintyIndicator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UncertaintyIndicator.tsx'|from 'components/prediction/UncertaintyIndicator.tsx'|g"
echo "Updating imports for UnifiedPredictionInterface.tsx -> UnifiedPredictionInterface.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UnifiedPredictionInterface.tsx'|from 'components/prediction/UnifiedPredictionInterface.tsx'|g"
echo "Updating imports for BetRecommendationList.test.tsx -> BetRecommendationList.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BetRecommendationList.test.tsx'|from 'components/prediction/BetRecommendationList.test.tsx'|g"
echo "Updating imports for DailyFantasyIntegration.tsx -> DailyFantasyIntegration.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/DailyFantasyIntegration.tsx'|from 'components/predictions/DailyFantasyIntegration.tsx'|g"
echo "Updating imports for FantasyPredictionEnhancer.tsx -> FantasyPredictionEnhancer.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/FantasyPredictionEnhancer.tsx'|from 'components/predictions/FantasyPredictionEnhancer.tsx'|g"
echo "Updating imports for LivePredictions.tsx -> LivePredictions.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/LivePredictions.tsx'|from 'components/predictions/LivePredictions.tsx'|g"
echo "Updating imports for PayoutPreviewPanel.tsx -> PayoutPreviewPanel.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PayoutPreviewPanel.tsx'|from 'components/predictions/PayoutPreviewPanel.tsx'|g"
echo "Updating imports for PredictionGenerator.tsx -> PredictionGenerator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PredictionGenerator.tsx'|from 'components/predictions/PredictionGenerator.tsx'|g"
echo "Updating imports for SHAPChart.tsx -> SHAPChart.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SHAPChart.tsx'|from 'components/predictions/SHAPChart.tsx'|g"
echo "Updating imports for UniversalPredictions.tsx -> UniversalPredictions.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UniversalPredictions.tsx'|from 'components/predictions/UniversalPredictions.tsx'|g"
echo "Updating imports for ProfilePage.tsx -> ProfilePage.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ProfilePage.tsx'|from 'components/profile/ProfilePage.tsx'|g"
echo "Updating imports for UnifiedProfile.tsx -> UnifiedProfile.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UnifiedProfile.tsx'|from 'components/profile/UnifiedProfile.tsx'|g"
echo "Updating imports for RealTimeDataStream.tsx -> RealTimeDataStream.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RealTimeDataStream.tsx'|from 'components/realtime/RealTimeDataStream.tsx'|g"
echo "Updating imports for EnhancedRevolutionaryInterface.tsx -> EnhancedRevolutionaryInterface.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/EnhancedRevolutionaryInterface.tsx'|from 'components/revolutionary/EnhancedRevolutionaryInterface.tsx'|g"
echo "Updating imports for RevolutionaryAccuracyInterface.tsx -> RevolutionaryAccuracyInterface.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RevolutionaryAccuracyInterface.tsx'|from 'components/revolutionary/RevolutionaryAccuracyInterface.tsx'|g"
echo "Updating imports for UltimateSettingsPage.tsx -> UltimateSettingsPage.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UltimateSettingsPage.tsx'|from 'components/settings/UltimateSettingsPage.tsx'|g"
echo "Updating imports for UnifiedSettingsInterface.tsx -> UnifiedSettingsInterface.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UnifiedSettingsInterface.tsx'|from 'components/settings/UnifiedSettingsInterface.tsx'|g"
echo "Updating imports for GlassCard.tsx -> GlassCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/GlassCard.tsx'|from 'components/ui/GlassCard.tsx'|g"
echo "Updating imports for GlassCard.tsx -> GlassCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/GlassCard.tsx'|from 'components/ui/GlassCard.tsx'|g"
echo "Updating imports for GlassCard.tsx -> GlassCard.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*GlassCard.tsx'|from 'components/ui/GlassCard.tsx'|g"
echo "Updating imports for RiskReasoningDisplay.tsx -> RiskReasoningDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RiskReasoningDisplay.tsx'|from 'components/shared/RiskReasoningDisplay.tsx'|g"
echo "Updating imports for DataUnavailableMessage.tsx -> DataUnavailableMessage.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/DataUnavailableMessage.tsx'|from 'components/shared/common/DataUnavailableMessage.tsx'|g"
echo "Updating imports for ErrorMessage.tsx -> ErrorMessage.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ErrorMessage.tsx'|from 'components/shared/common/ErrorMessage.tsx'|g"
echo "Updating imports for RiskLevelIndicator.tsx -> RiskLevelIndicator.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RiskLevelIndicator.tsx'|from 'components/shared/common/RiskLevelIndicator.tsx'|g"
echo "Updating imports for SafeButton.tsx -> SafeButton.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SafeButton.tsx'|from 'components/shared/common/SafeButton.tsx'|g"
echo "Updating imports for ToastProvider.tsx -> ToastProvider.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ToastProvider.tsx'|from 'components/shared/common/ToastProvider.tsx'|g"
echo "Updating imports for ValidationStatus.tsx -> ValidationStatus.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ValidationStatus.tsx'|from 'components/shared/common/ValidationStatus.tsx'|g"
echo "Updating imports for BettingButton.tsx -> BettingButton.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingButton.tsx'|from 'components/shared/common/buttons/BettingButton.tsx'|g"
echo "Updating imports for BettingButtonGroup.tsx -> BettingButtonGroup.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/BettingButtonGroup.tsx'|from 'components/shared/common/buttons/BettingButtonGroup.tsx'|g"
echo "Updating imports for QuickBetButton.tsx -> QuickBetButton.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/QuickBetButton.tsx'|from 'components/shared/common/buttons/QuickBetButton.tsx'|g"
echo "Updating imports for MainLayout.tsx -> MainLayout.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*layouts/MainLayout.tsx'|from 'components/shared/common/layout/MainLayout.tsx'|g"
echo "Updating imports for MainLayout.tsx -> MainLayout.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/MainLayout.tsx'|from 'components/shared/common/layout/MainLayout.tsx'|g"
echo "Updating imports for ThemeProvider.tsx -> ThemeProvider.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*providers/ThemeProvider.tsx'|from 'components/shared/common/ThemeProvider.tsx'|g"
echo "Updating imports for ThemeProvider.tsx -> ThemeProvider.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*theme/ThemeProvider.tsx'|from 'components/shared/common/ThemeProvider.tsx'|g"
echo "Updating imports for advanced-charts.tsx -> advanced-charts.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/advanced-charts.tsx'|from 'components/shared/advanced-charts.tsx'|g"
echo "Updating imports for button.tsx -> button.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*button.tsx'|from 'components/shared/button.tsx'|g"
echo "Updating imports for card.tsx -> card.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*card.tsx'|from 'components/shared/card.tsx'|g"
echo "Updating imports for GlowButton.tsx -> GlowButton.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/GlowButton.tsx'|from 'components/ui/GlowButton.tsx'|g"
echo "Updating imports for GlowButton.tsx -> GlowButton.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*GlowButton.tsx'|from 'components/ui/GlowButton.tsx'|g"
echo "Updating imports for NotificationToast.tsx -> NotificationToast.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/shared/NotificationToast.tsx'|from 'components/ui/NotificationToast.tsx'|g"
echo "Updating imports for NotificationToast.tsx -> NotificationToast.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*NotificationToast.tsx'|from 'components/ui/NotificationToast.tsx'|g"
echo "Updating imports for PredictionSummaryCard.test.tsx -> PredictionSummaryCard.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PredictionSummaryCard.test.tsx'|from 'components/shared/PredictionSummaryCard.test.tsx'|g"
echo "Updating imports for tabs-simple.tsx -> tabs-simple.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/tabs-simple.tsx'|from 'components/shared/tabs-simple.tsx'|g"
echo "Updating imports for UnifiedMoneyMakerIntegration.tsx -> UnifiedMoneyMakerIntegration.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UnifiedMoneyMakerIntegration.tsx'|from 'components/strategy/UnifiedMoneyMakerIntegration.tsx'|g"
echo "Updating imports for UnifiedStrategyConfig.tsx -> UnifiedStrategyConfig.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UnifiedStrategyConfig.tsx'|from 'components/strategy/UnifiedStrategyConfig.tsx'|g"
echo "Updating imports for UnifiedStrategyEngineDisplay.tsx -> UnifiedStrategyEngineDisplay.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UnifiedStrategyEngineDisplay.tsx'|from 'components/strategy/UnifiedStrategyEngineDisplay.tsx'|g"
echo "Updating imports for IntelligentMergedInterface.tsx -> IntelligentMergedInterface.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/IntelligentMergedInterface.tsx'|from 'components/unified/IntelligentMergedInterface.tsx'|g"
echo "Updating imports for ArbitrageHunter.tsx -> ArbitrageHunter.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ArbitrageHunter.tsx'|from 'components/user-friendly/ArbitrageHunter.tsx'|g"
echo "Updating imports for ComprehensiveUserProfile.tsx -> ComprehensiveUserProfile.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ComprehensiveUserProfile.tsx'|from 'components/user-friendly/ComprehensiveUserProfile.tsx'|g"
echo "Updating imports for ConsolidatedUserProfile.tsx -> ConsolidatedUserProfile.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/ConsolidatedUserProfile.tsx'|from 'components/user-friendly/ConsolidatedUserProfile.tsx'|g"
echo "Updating imports for PortfolioCommander.tsx -> PortfolioCommander.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/PortfolioCommander.tsx'|from 'components/user-friendly/PortfolioCommander.tsx'|g"
echo "Updating imports for RiskEngineInterface.tsx -> RiskEngineInterface.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/RiskEngineInterface.tsx'|from 'components/user-friendly/RiskEngineInterface.tsx'|g"
echo "Updating imports for Settings.tsx -> Settings.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*pages/Settings.tsx'|from 'components/user-friendly/Settings.tsx'|g"
echo "Updating imports for SettingsTest.tsx -> SettingsTest.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SettingsTest.tsx'|from 'components/user-friendly/SettingsTest.tsx'|g"
echo "Updating imports for SimpleSettings.tsx -> SimpleSettings.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/SimpleSettings.tsx'|from 'components/user-friendly/SimpleSettings.tsx'|g"
echo "Updating imports for UltimateOpportunityScanner.tsx -> UltimateOpportunityScanner.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UltimateOpportunityScanner.tsx'|from 'components/user-friendly/UltimateOpportunityScanner.tsx'|g"
echo "Updating imports for UserFriendlyApp.tsx -> UserFriendlyApp.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*components/user-friendly/__mocks__/UserFriendlyApp.tsx'|from 'components/user-friendly/UserFriendlyApp.tsx'|g"
echo "Updating imports for UserFriendlyApp_fixed.tsx -> UserFriendlyApp_fixed.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UserFriendlyApp_fixed.tsx'|from 'components/user-friendly/UserFriendlyApp_fixed.tsx'|g"
echo "Updating imports for UserFriendlyDashboard_Production.tsx -> UserFriendlyDashboard_Production.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tmp/UserFriendlyDashboard_Production.tsx'|from 'components/user-friendly/UserFriendlyDashboard_Production.tsx'|g"
echo "Updating imports for PropOllama.test.tsx -> PropOllama.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*services/__tests__/PropOllama.test.tsx'|from 'components/user-friendly/PropOllama.test.tsx'|g"
echo "Updating imports for Dashboard.test.tsx -> Dashboard.test.tsx"
find frontend/src -name '*.tsx' -o -name '*.jsx' | xargs sed -i.bak "s|from '.*tests/unit/components/Dashboard.test.tsx'|from 'pages/Dashboard.test.tsx'|g"

echo "Import update phase complete."
