"""Add historical data models (Casino, Score, GameSpread)

Revision ID: 079780825cba
Revises: 37f2139975d0
Create Date: 2025-07-15 17:29:06.566029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079780825cba'
down_revision: Union[str, Sequence[str], None] = '37f2139975d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
