"""Add teams, events, odds tables

Revision ID: 504fcf5dc2f5
Revises: 6e6dad7a7f13
Create Date: 2025-07-15 18:31:16.730587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504fcf5dc2f5'
down_revision: Union[str, Sequence[str], None] = '6e6dad7a7f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
