"""Update historical schema

Revision ID: 6e6dad7a7f13
Revises: a488fec67a2b
Create Date: 2025-07-15 17:36:56.811455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6dad7a7f13'
down_revision: Union[str, Sequence[str], None] = 'a488fec67a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_spreads', sa.Column('odds_metadata', sa.String(), nullable=True))
    op.create_index(op.f('ix_game_spreads_casino_id'), 'game_spreads', ['casino_id'], unique=False)
    op.create_index(op.f('ix_game_spreads_match_id'), 'game_spreads', ['match_id'], unique=False)
    op.create_index(op.f('ix_scores_match_id'), 'scores', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_match_id'), table_name='scores')
    op.drop_index(op.f('ix_game_spreads_match_id'), table_name='game_spreads')
    op.drop_index(op.f('ix_game_spreads_casino_id'), table_name='game_spreads')
    op.drop_column('game_spreads', 'odds_metadata')
    # ### end Alembic commands ###
