"""sync models and schema

Revision ID: 9beb31b07eb3
Revises: f06f8a0fc07c
Create Date: 2025-07-27 22:38:27.830983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9beb31b07eb3'
down_revision: Union[str, Sequence[str], None] = 'f06f8a0fc07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=512), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key_encrypted'), 'users', ['api_key_encrypted'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table('casinos')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_scores_match_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_game_spreads_casino_id'), table_name='game_spreads')
    op.drop_index(op.f('ix_game_spreads_match_id'), table_name='game_spreads')
    op.drop_table('game_spreads')
    op.create_index(op.f('ix_odds_event_id'), 'odds', ['event_id'], unique=False)
    op.create_index(op.f('ix_odds_team_id'), 'odds', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odds_team_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_event_id'), table_name='odds')
    op.create_table('game_spreads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=True),
    sa.Column('casino_id', sa.INTEGER(), nullable=True),
    sa.Column('spread', sa.NUMERIC(precision=4, scale=1), nullable=True),
    sa.Column('home_team_line', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('away_team_line', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('odds_metadata', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['casino_id'], ['casinos.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_spreads_match_id'), 'game_spreads', ['match_id'], unique=False)
    op.create_index(op.f('ix_game_spreads_casino_id'), 'game_spreads', ['casino_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=True),
    sa.Column('home_score', sa.INTEGER(), nullable=True),
    sa.Column('away_score', sa.INTEGER(), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_match_id'), 'scores', ['match_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('home_team', sa.VARCHAR(), nullable=False),
    sa.Column('away_team', sa.VARCHAR(), nullable=False),
    sa.Column('sport', sa.VARCHAR(), nullable=False),
    sa.Column('league', sa.VARCHAR(), nullable=False),
    sa.Column('season', sa.VARCHAR(), nullable=True),
    sa.Column('week', sa.INTEGER(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('home_score', sa.INTEGER(), nullable=True),
    sa.Column('away_score', sa.INTEGER(), nullable=True),
    sa.Column('venue', sa.VARCHAR(), nullable=True),
    sa.Column('weather_conditions', sa.VARCHAR(), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('external_id', sa.VARCHAR(), nullable=True),
    sa.Column('sportsradar_id', sa.VARCHAR(), nullable=True),
    sa.Column('the_odds_api_id', sa.VARCHAR(), nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), nullable=True),
    sa.Column('has_live_odds', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('casinos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key_encrypted'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
