name: Backfill-focused tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backfill-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Create SQLite DB
        run: |
          python scripts/create_test_db.py
      - name: Run migrations (alembic upgrade head)
        run: |
          cd backend && alembic upgrade head || true
      - name: Seed bookmakers
        run: |
          python scripts/run_seed_bookmakers.py
      - name: Run focused tests
        run: |
          pytest backend/tests/test_bestline_name_backfill.py -q
